name: CI/CD Pipeline - Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code from GitHub
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 4: Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 6: Log in to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Step 7: Build Docker Images
    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yml build

    # Step 8: Tag and Push Docker Images to Docker Hub
    - name: Tag and Push Docker Images to Docker Hub
      run: |
        docker tag my-image:latest ${{ secrets.DOCKER_USERNAME }}/my-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest

    # Step 9: Tag and Push Docker Images to Amazon ECR
    - name: Tag and Push Docker Images to Amazon ECR
      run: |
        docker tag my-image:latest public.ecr.aws/r0i6v8x7/${{ secrets.ECR_REPOSITORY }}:latest
        docker push public.ecr.aws/r0i6v8x7/${{ secrets.ECR_REPOSITORY }}:latest
