name: CI/CD Pipeline with Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI Job: Build, Test, and Push Docker Images
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yml build

    - name: Run Tests in Containers
      run: |
        # Run the tests inside the Docker containers
        docker-compose -f docker-compose.yml run --rm user_mangment pytest /app/tests
        docker-compose -f docker-compose.yml run --rm en2ar_service pytest /app/tests
        docker-compose -f docker-compose.yml run --rm ar2en_service pytest /app/tests
        docker-compose -f docker-compose.yml run --rm text-summarization-service pytest /app/tests

    - name: Push Docker Images to Docker Hub
      run: |
        docker-compose -f docker-compose.yml push




